### PR TITLE
Use unix linefeed as a line separator

### PR DESCRIPTION
**Pull request by techtonik**
This makes .ndbx files saved in the same way on Linux
and Windows. Fixes issue #426

### CODE REVIEW

**Comment by fdb** [comment]
Thanks! I'll release this Very Soon™

**Comment by techtonik** [comment]
@fdb so are there any news on release? =)

**Comment by fdb** [comment]
I'm currently on holiday so I'm not able to make a release, sorry.

**Comment by techtonik** [comment]
@fdb take your time. No problem. =)

**Pull request merged**
